export const MOVIE_LOAD_REQUEST = 'MOVIES/LOAD/REQUESTED';
export const MOVIE_LOAD_FAILED = 'MOVIES/LOAD/FAILED';
export const MOVIE_LOAD_SUCCESS = 'MOVIES/LOAD/SUCCESS';
export const MOVIE_DETAIL_LOAD_REQUEST = 'MOVIES-DETAIL/LOAD/REQUESTED';
export const MOVIE_DETAIL_LOAD_FAILED = 'MOVIES-DETAIL/LOAD/FAILED';
export const MOVIE_DETAIL_LOAD_SUCCESS = 'MOVIES-DETAIL/LOAD/SUCCESS';